### PR TITLE
you cannot resolve forces in the same loop

### PR DESCRIPTION
**Pull request by vance**
in which you accumulate them. I did not functionally test this, but it should work.

### CODE REVIEW

**Comment by ybrodsky** [comment]
What's the difference?

There are two loops. 

```
Outer loop:
  Get object i
  Inner loop:
    Get object i + 1
    Calculate the force that i + 1 generates over i
    Store that force
  End Inner loop
  Apply forces to object i
End Outer loop  
```

With your change is the same except you are applying the forces afterwards. What would be the difference or why you say I shouldnt be applying them in the outer loop? (honestly asking, dont mean to sound cocky)

**Comment by FlavorScape** [comment]
Basic phsyics accumulation problem. Some of the inner loop will have bodies that already have the t2 positions since you applied them in the outer loop. You're using mutated positions as an input in the inner loop. This code is correct: http://justfound.co/gravity/grav.js
your definition of inner loop is not i +1. it is n, where [n] can be an object with forces already applied. element at [0] will calculate based on t1 vectors. Element at [len/2] will compute forces after half the objects have transformed to t2 positions. Element at [len] will compute against all objects skewed positions.

**Comment by ybrodsky** [comment]
Okay, I see your point. The problem is the second interval that's running which could have already moved the object with the applied force, thus creating the problem you describe.
In fact, this might be the "why" for a little bug I noticed. Will check later to confirm.

Thanks

**Comment by vance** [comment]
no problem. This would cause objects sometimes falling too fast and hitting the other body, or sometimes slingshot outward when not supposed to.  I made this same mistake once when working on a rigid body simulation. I was trying to optimize the accumulation over parallel CPUs, only to realize I had to wait for all calculations to come back, then send the entire new values back to the different threads for computation, I couldn't just use them in memory.

**Comment by ybrodsky** [comment]
Yes, this is exactly what I noticed. When programmatically adding two objects you can see that the way they behave it's not consistent. Indeed this might have been the cause.

**Pull request merged**
